AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an EC2 instance to run a static website (kittens) application deployed with Apache Web Server

Resources:
  SecurityGroupofServer:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: for ssh http #required
      GroupName: oscarsgname
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
   
      
  
  OscarCFInstance :
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      KeyName: cf-web-app
      SecurityGroups:
        - !Ref SecurityGroupofServer
      Tags:
        - Key: Name
          Value: Web Server of xxxxx
      UserData: 
        Fn::Base64:
          !Sub | 
            #! /bin/bash
            sudo yum update -y
            sudo yum install python3 -y
            sudo yum install httpd -y
            sudo systemctl start httpd
            sudo systemctl status httpd
            sudo systemctl enable httpd
            sudo chmod -R 777 /var/www/html
            cd /var/www/html

            wget https://raw.githubusercontent.com/fianchettogianni/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/README.md
            wget https://raw.githubusercontent.com/fianchettogianni/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
            wget https://raw.githubusercontent.com/fianchettogianni/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
            wget https://raw.githubusercontent.com/fianchettogianni/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
            wget https://raw.githubusercontent.com/fianchettogianni/clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
            
            sudo systemctl restart httpd
            systemctl enable httpd

Outputs:
  InstanceId:
    Description: InstanceId of the first EC2 instance
    Value: !Ref OscarCFInstance
  PublicDNS:
    Description: Public DNS Name of the EC2 instance
    Value: !Join 
      - "://"
      - - "http"
        - !GetAtt 
          - OscarCFInstance
          - PublicDnsName





        