AWSTemplateFormatVersion: 2010-09-09
Description: This template creates an EC2 instance to run a static website (kittens) application deployed with Apache Web Server
Resources:
  OscarCFInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      KeyName: aaa
      SecurityGroups:
        - HTTPli for web Browser
      Tags:
        - Key: Name
          Value: oscar-cf-instance-kittens
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash

            sudo yum update -y

            sudo yum install python3 -y

            sudo yum install httpd -y

            DATE_TIME=`date`

            sudo systemctl start httpd

            sudo systemctl status httpd

            sudo systemctl enable httpd

            sudo chmod -R 777 /var/www/html

            cd /var/www/html

            wget https://raw.githubusercontent.com/polymerr/Clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/README.md

            mkdir kittens

            cd kittens
            
            wget https://raw.githubusercontent.com/polymerr/Clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html

            wget https://raw.githubusercontent.com/polymerr/Clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg

            wget https://raw.githubusercontent.com/polymerr/Clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg

            wget https://raw.githubusercontent.com/polymerr/Clarusway-aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
 
            cd ..
            
            sudo systemctl restart httpd

            systemctl enable httpd


            